[workspace]
resolver = "2"
members = [
    "packages/ui",
    "packages/app",
    "packages/editor",
    "packages/sync-dto",
    "packages/api-sdk",
    "packages/store-sdk",
    "apps/web",
    "apps/desktop",
    "apps/mobile",
    "apps/api",
    "apps/landing",
]

[workspace.dependencies]
dioxus = { version = "0.7.1" }
dioxus-i18n = { version = "0.5.1" }
unic-langid = { version = "0.9", features = ["macros"] }

# workspace
ui = { path = "packages/ui" }
app = { path = "packages/app" }
editor = { path = "packages/editor" }
sync-dto = { path = "packages/sync-dto" }
api-sdk = { path = "packages/api-sdk" }
store-sdk = { path = "packages/store-sdk" }
