[workspace]
resolver = "2"
members = [
    "packages/ui",
    "packages/app",
    "apps/web",
    "apps/desktop",
    "apps/mobile",
    "apps/api",
    "apps/landing",
]

[workspace.dependencies]
dioxus = { version = "0.7.1" }

# workspace
ui = { path = "packages/ui" }
app = { path = "packages/app" }
api = { path = "apps/api" }
