[package]
name = "landing"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["router"] }
dioxus-i18n = { workspace = true }
unic-langid = { workspace = true }

[features]
default = []
web = ["dioxus/web", "dioxus/fullstack"]
server = ["dioxus/fullstack", "dioxus/server"]
