[package]
name = "desktop"
version = "0.3.0"
edition = "2021"

[[bin]]
name = "light-notes"
path = "src/main.rs"

[dependencies]
dioxus = { workspace = true, features = ["router", "fullstack"] }
app = { workspace = true }
ui = { workspace = true }

[features]
default = []
desktop = ["dioxus/desktop"]
server = ["dioxus/server", "app/server", "ui/server"]
