[bundle]
identifier = "dev.lightnotes.desktop"
publisher = "LightNotes"
icon = ["icons/icon.png"]

[bundle.windows]
webview_install_mode = { OfflineInstaller = { silent = true } }

[bundle.windows.sign_command]
cmd = "powershell"
args = [
  "-NoProfile",
  "-ExecutionPolicy",
  "Bypass",
  "-File",
  "scripts/windows-sign.ps1",
  "-Path",
  "%1",
]

[bundle.windows.wix]
upgrade_code = "6e851b49-e3ee-5439-8aa4-8209e2386b03"

[bundle.windows.nsis]
install_mode = "CurrentUser"
